import { mkdirSync, readFileSync, readdirSync, rmSync, writeFileSync } from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import ts from 'typescript';

/*
 * Codegen for KESQ query placement.  Scans src/queries for modules whose
 * filename declares a tier and mirrors them into gen/, which the package.json
 * "imports" field routes per environment:
 *
 *   *.flex.ts    flexible — may run in the browser or on the query server
 *   *.server.ts  server-only — the client gets a bare wire reference
 *
 * For each module this emits:
 *
 *   gen/client/<stem>.ts  every export wrapped via wrapFlex (flexible) or
 *                         reduced to a serverRef stub (server-only, imported
 *                         type-only so the implementation stays out of the
 *                         browser bundle)
 *   gen/server/<stem>.ts  every export wrapped via wrapFlex — on the server
 *                         the implementation is always available
 *   gen/server/registry.ts  the raw factories keyed by "<stem>#<export>",
 *                           for the query server's subscribe dispatch
 *
 * Plain modules (no suffix) are ignored: local-only queries need no codegen.
 */

const root = path.dirname(fileURLToPath(import.meta.url));
const queryDir = path.join(root, 'src', 'queries');
const genDir = path.join(root, 'gen');

const TIER_SUFFIX = /\.(flex|server)\.ts$/;
const HEADER = '// Code generated by gen-queries.mjs; do not edit.\n';

function fail(msg) {
  console.error(`gen-queries: ${msg}`);
  process.exit(1);
}

/** Runtime export names of a module, in declaration order. */
function collectExportNames(file) {
  const source = ts.createSourceFile(
    file,
    readFileSync(file, 'utf8'),
    ts.ScriptTarget.Latest,
    false,
  );
  const names = [];
  for (const stmt of source.statements) {
    const mods = ts.canHaveModifiers(stmt) ? (ts.getModifiers(stmt) ?? []) : [];
    const has = (kind) => mods.some((m) => m.kind === kind);
    if (ts.isExportAssignment(stmt) || has(ts.SyntaxKind.DefaultKeyword)) {
      fail(`${file}: default exports are not supported in query modules`);
    }
    if (ts.isExportDeclaration(stmt)) {
      if (!stmt.exportClause || !ts.isNamedExports(stmt.exportClause)) {
        fail(`${file}: export * is not supported in query modules`);
      }
      if (stmt.isTypeOnly) continue;
      for (const spec of stmt.exportClause.elements) {
        if (!spec.isTypeOnly) names.push(spec.name.text);
      }
      continue;
    }
    if (!has(ts.SyntaxKind.ExportKeyword)) continue;
    if (ts.isTypeAliasDeclaration(stmt) || ts.isInterfaceDeclaration(stmt)) continue;
    if (ts.isFunctionDeclaration(stmt)) {
      names.push(stmt.name.text);
    } else if (ts.isVariableStatement(stmt)) {
      for (const d of stmt.declarationList.declarations) {
        if (!ts.isIdentifier(d.name)) {
          fail(`${file}: destructuring exports are not supported in query modules`);
        }
        names.push(d.name.text);
      }
    } else {
      fail(`${file}: only function factories may be exported from query modules`);
    }
  }
  return names;
}

function findQueryModules(dir) {
  const out = [];
  for (const entry of readdirSync(dir, { withFileTypes: true })) {
    const full = path.join(dir, entry.name);
    if (entry.isDirectory()) out.push(...findQueryModules(full));
    else if (TIER_SUFFIX.test(entry.name)) out.push(full);
  }
  return out.sort();
}

/** Extensionless import specifier for `target` from a file in `fromDir`. */
function importPath(fromDir, target) {
  const rel = path.relative(fromDir, target).split(path.sep).join('/');
  return (rel.startsWith('.') ? rel : './' + rel).replace(/\.ts$/, '');
}

const modules = findQueryModules(queryDir).map((file) => {
  const tier = TIER_SUFFIX.exec(file)[1];
  const stem = path
    .relative(queryDir, file)
    .replace(TIER_SUFFIX, '')
    .split(path.sep)
    .join('/');
  return { file, tier, stem, names: collectExportNames(file) };
});

const seen = new Map();
for (const m of modules) {
  if (m.stem === 'registry') fail(`${m.file}: the stem "registry" is reserved`);
  const other = seen.get(m.stem);
  if (other) fail(`query modules collide on "${m.stem}": ${other.file} and ${m.file}`);
  seen.set(m.stem, m);
}

rmSync(genDir, { recursive: true, force: true });

function emit(relPath, body) {
  const file = path.join(genDir, relPath);
  mkdirSync(path.dirname(file), { recursive: true });
  writeFileSync(file, HEADER + body);
}

for (const m of modules) {
  const dir = (side) => path.join(genDir, side, path.dirname(m.stem));
  const src = (side) => importPath(dir(side), m.file);
  const flex = (side) => importPath(dir(side), path.join(root, 'src', 'flex.ts'));
  const id = (name) => `${m.stem}#${name}`;

  const wrapped =
    `import { wrapFlex } from '${flex('client')}';\n` +
    `import * as m from '${src('client')}';\n\n` +
    m.names.map((n) => `export const ${n} = wrapFlex('${id(n)}', m.${n});\n`).join('');

  if (m.tier === 'flex') {
    emit(`client/${m.stem}.ts`, wrapped);
  } else {
    emit(
      `client/${m.stem}.ts`,
      `import { serverRef } from '${flex('client')}';\n` +
        `import type * as m from '${src('client')}';\n\n` +
        m.names.map((n) => `export const ${n} = serverRef<typeof m.${n}>('${id(n)}');\n`).join(''),
    );
  }
  emit(`server/${m.stem}.ts`, wrapped);
}

const registry =
  modules.map((m, i) => `import * as m${i} from '${importPath(path.join(genDir, 'server'), m.file)}';\n`).join('') +
  `\nexport const queries: Record<string, ((...args: any[]) => any) | undefined> = {\n` +
  modules.flatMap((m, i) => m.names.map((n) => `  '${m.stem}#${n}': m${i}.${n},\n`)).join('') +
  `};\n`;
emit('server/registry.ts', registry);

const total = modules.reduce((sum, m) => sum + m.names.length, 0);
console.log(`gen-queries: ${total} queries from ${modules.length} modules -> gen/`);
